import {chromium} from 'playwright'; import fs from 'fs'; import {APPS} from './apps.mjs';
const key=process.argv[2]; const run=process.argv[3]||1; const A=APPS[key];
const b=await chromium.launch({channel:'chrome',headless:false,args:['--enable-webgl','--ignore-gpu-blocklist','--disable-renderer-backgrounding','--disable-background-timer-throttling','--disable-backgrounding-occluded-windows','--disable-frame-rate-limit']});
const ctx=await b.newContext({viewport:{width:1600,height:900}}); const p=await ctx.newPage();
const t0=Date.now(); await p.goto(`http://localhost:${A.port}/`,{waitUntil:'load'}); const tLoad=Date.now()-t0;
await p.addScriptTag({content:`window.__ft=[];window.__ph='load';(function f(t){window.__ft.push([t,window.__ph]);requestAnimationFrame(f)})(0);window.__lt=[];try{new PerformanceObserver(l=>l.getEntries().forEach(e=>window.__lt.push([e.startTime,e.duration,window.__ph]))).observe({entryTypes:['longtask']})}catch(e){}`});
const cdp=await ctx.newCDPSession(p); await cdp.send('Performance.enable');
const m=async()=>Object.fromEntries((await cdp.send('Performance.getMetrics')).metrics.map(x=>[x.name,x.value]));
await p.waitForTimeout(3000);
await p.click(A.intro).catch(()=>{});await p.waitForTimeout(1000);
await p.click(A.extreme);await p.click(A.seawall);await p.mouse.move(750,560);await p.mouse.move(800,560,{steps:5});await p.mouse.click(800,560);await p.keyboard.press('Escape');await p.mouse.move(150,720);await p.waitForTimeout(500);
const res={key,run,loadMs:tLoad};
await p.evaluate(`window.__ph='idle'`);const m0=await m();await p.waitForTimeout(6000);const m1=await m();
await p.evaluate(`window.__ph='wave'`);await p.click(A.launch);await p.waitForTimeout(50000);const m2=await m();
res.mem=await p.evaluate(()=>performance.memory?{used:performance.memory.usedJSHeapSize/1048576,total:performance.memory.totalJSHeapSize/1048576}:null);
const d=await p.evaluate(()=>({ft:window.__ft,lt:window.__lt}));
const stat=(ph)=>{const f=d.ft.filter(x=>x[1]===ph).map(x=>x[0]);const dt=[];for(let i=1;i<f.length;i++)dt.push(f[i]-f[i-1]);dt.sort((a,b)=>a-b);
 const dur=(f[f.length-1]-f[0])/1000;const q=x=>dt[Math.min(dt.length-1,Math.floor(dt.length*x))];
 const lt=d.lt.filter(x=>x[2]===ph);return {fps:+(dt.length/dur).toFixed(1),p50ms:+q(.5).toFixed(1),p95ms:+q(.95).toFixed(1),p99ms:+q(.99).toFixed(1),maxMs:+dt[dt.length-1].toFixed(0),framesOver50ms:dt.filter(x=>x>50).length,longTasks:lt.length,longTaskMs:+lt.reduce((s,x)=>s+x[1],0).toFixed(0)}};
res.idle=stat('idle');res.wave=stat('wave');
res.mainThreadBusyIdle=+((m1.TaskDuration-m0.TaskDuration)/6*100).toFixed(0);res.mainThreadBusyWave=+((m2.TaskDuration-m1.TaskDuration)/50*100).toFixed(0);
res.domNodes=m2.Nodes;res.jsHeapMB=+(m2.JSHeapUsedSize/1048576).toFixed(0);
fs.writeFileSync(`perf_${key}_${run}.json`,JSON.stringify(res));console.log(JSON.stringify(res));await b.close();
