import {chromium} from 'playwright'; import fs from 'fs'; import {APPS} from './apps.mjs';
const key=process.argv[2]; const A=APPS[key]; const PRE=3000, RUN=55000;
const dir=`frames_${key}`; fs.rmSync(dir,{recursive:true,force:true}); fs.mkdirSync(dir);
const b=await chromium.launch({channel:'chrome',headless:false,args:['--enable-webgl','--ignore-gpu-blocklist','--disable-renderer-backgrounding','--disable-background-timer-throttling','--disable-backgrounding-occluded-windows']});
const p=await (await b.newContext({viewport:{width:1600,height:900}})).newPage();
const errs=[];p.on('pageerror',e=>errs.push(e.message));
await p.goto(`http://localhost:${A.port}/`);await p.waitForTimeout(3000);
await p.click(A.intro).catch(()=>{});await p.waitForTimeout(1000);
await p.click(A.severe);await p.click(A.seawall);
await p.mouse.move(750,560);await p.mouse.move(800,560,{steps:5});await p.waitForTimeout(400);
await p.mouse.click(800,560);await p.waitForTimeout(500);await p.mouse.move(1000,880);await p.waitForTimeout(500);
const cdp=await p.context().newCDPSession(p); const frames=[];let n=0;
cdp.on('Page.screencastFrame',async f=>{const t=f.metadata.timestamp*1000;const name=`${dir}/${String(n++).padStart(6,'0')}.jpg`;fs.writeFileSync(name,Buffer.from(f.data,'base64'));frames.push({name,t});cdp.send('Page.screencastFrameAck',{sessionId:f.sessionId}).catch(()=>{});});
await cdp.send('Page.startScreencast',{format:'jpeg',quality:92,maxWidth:1600,maxHeight:900,everyNthFrame:1});
await p.waitForTimeout(PRE);
await p.click(A.launch); const L=Date.now();
await p.waitForTimeout(RUN);
await cdp.send('Page.stopScreencast');
fs.writeFileSync(`frames_${key}.json`,JSON.stringify({frames,L,pre:PRE,run:RUN,errs}));
console.log(key,frames.length,'frames',errs.slice(0,3));await b.close();
